"""third  Migration

Revision ID: 68b18f7f357f
Revises: ab87bdc50ef3
Create Date: 2020-06-18 20:44:18.037791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b18f7f357f'
down_revision = 'ab87bdc50ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pass_secure')
    # ### end Alembic commands ###
